export type { Encounter, EncounterStatus, ClinicalNote } from "./core/types"
export { parseNoteText, formatNoteText, EMPTY_NOTE } from "./core/types"
export { useEncounters } from "./hooks/use-encounters"
export { EncounterList } from "./ui/encounter-list"
export { IdleView } from "./ui/idle-view"
export { NewEncounterForm } from "./ui/new-encounter-form"
export { NoteEditor } from "./ui/note-editor"
export type { ClinicalNoteRequest } from "./services/clinical-note-generator"
export { createClinicalNoteText } from "./services/clinical-note-generator"
